### ISSUE TITLE
Create a New event to notify when new flow statistics is available

### ISSUE THREAD

**Issue by cmagnobarbosa** [kytos/of_core#122]
As suggested by @italovalcy, in the issue [#124](https://github.com/kytos/flow_manager/issues/124), Today the `of_core` NApp, does not have an event to notify when new statistics the flow is available. This new feature allows the NApp to use on-demand flow statistics (like the `flow_manager` NApp, to check the flows' consistency). Therefore, its necessary implement this new event in the `of_core`. In additional, this modification it's necessary to consistency check work properly.

**Comment by italovalcy** [comment]
@cmagnobarbosa this was fixed by #123
