### ISSUE TITLE
Add support for OF Handshake Complete event

### ISSUE THREAD

**Issue by viniarck** [kytos/of_core#22]
Hi Team, 

I was working on a Napp that needed to bootstrap some flows and I've realized that without the OF Handshake Event I had to rely on '.*.switch.(new|reconnected)' events from topology, but often times the switch was not ready to install flows since the handshake was not fully completed and the handshake depends on waiting for features reply, and in real networks, this can take a few seconds. So, it would be nice for NApps to have this OF Handshake Complete event to rely on.

Let me know if I should send a PR or if you have a better suggestion to handle this:
https://github.com/viniciusarcanjo/of_core/commit/b1ed3a59cdae12039bb417e0bbf5f22449e626b1

**Comment by beraldoleal** [comment]
I think that is a good idea to have an event after the handshake process.

In your code, I would suggest to replace the event name to something like: "kytos.of_core.handshake.completed".

**Comment by viniarck** [comment]
I'm closing this issue since it's been merged.
