### ISSUE TITLE
Handle openflow error OFPBAC_BAD_OUT_PORT

### ISSUE THREAD

**Issue by cmagnobarbosa** [kytos/of_core#80]
What should Kytos do with OF error OFPBAC_BAD_OUT_PORT? According to the OF1.3 spec: "If any action references a port that will never be valid on a switch, the switch must return an ofp_error_msg with OFPET_BAD_ACTION type and OFPBAC_BAD_OUT_PORT code."

Possible solution: mark the port as UNAVAILABLE/FAILED (or something similar) and wait for an administrative action:
- STATUS: enabled/disabled/failed/maintenance
- LAST_STATUS_CHANGE: timestamp
  - so that we can keep track and expire a FAILED state
  - Cisco has something like this on switch ports

**Comment by ajoaoff** [comment]
That error also happens when you try to use a port that does not exist in the switch. In that case, I there will be no interface to be marked.

**Comment by gleybersonandrade** [comment]
Related kytos/of_core#79
