### ISSUE TITLE
OFPT_ERROR: BadActionCode Better Description Needed

### ISSUE THREAD

**Issue by dgarc330** [kytos/of_core#99]
Any OFPT_ERROR should provide the name or IP address of the source switch sending it. Also the transaction id.

2020-11-12 17:49:48,683 - ERROR [kytos.napps.kytos/of_core] (Thread-41332) OFPT_ERROR: BadActionCode.OFPBAC_BAD_TYPE

**Comment by dgarc330** [comment]
This kind of information would be very helpful for troubleshooting scenarios.

**Comment by josemauro** [comment]
Hey @dgarc330 the change to include the information that you asked it was already merged. So, I am closing this issue.
